/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.f4grx.audiobpsk;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Line;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.Mixer;
import javax.sound.sampled.SourceDataLine;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author slo
 */
public class sender extends javax.swing.JFrame {
    
    private boolean txtMsgClicked;
   
    private Player p;
    
    /**
     * Creates new form sender
     */
    public sender() {
        initComponents();
        txtMsgClicked = false;
        DefaultComboBoxModel<MixerProxy> lm = new DefaultComboBoxModel<>();
        cmbDevices.setModel(lm);
        
        Mixer.Info[] ms = AudioSystem.getMixerInfo();
        for(Mixer.Info m: ms) {
            Mixer mx = AudioSystem.getMixer(m);
            System.out.println("mixer : "+mx.getMixerInfo().getName());
            Line.Info[] li;
            int src = 0;
            int tgt = 0;
            li = mx.getSourceLineInfo();
            for(Line.Info l: li) {
                src++;
                try {
                    System.out.println("  source: "+mx.getLine(l).toString());
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(sender.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            li = mx.getTargetLineInfo();
            for(Line.Info l: li) {
                tgt++;
                try {
                    System.out.println("  target: "+mx.getLine(l).toString());
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(sender.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(src>0) {
                lm.addElement(new MixerProxy(mx));
                System.out.println("    added");
            }
        }
    }

    private void open(int freq) {
        p=null;
        if(freq<100 || freq > 10000) {
            return;
        }
        Line line;
        DefaultComboBoxModel<MixerProxy> mod = (DefaultComboBoxModel<MixerProxy>) cmbDevices.getModel();
        Mixer m = mod.getElementAt(cmbDevices.getSelectedIndex()).getMixer();
        Line.Info[] li = m.getSourceLineInfo();
        Line curline = null;
        for(Line.Info l: li) {
            try {
                line = m.getLine(l);
                System.out.println("  source: "+line.toString());
                if(line instanceof SourceDataLine) {
                    curline = line;
                    p = new Player((SourceDataLine)curline, freq);
                    p.setBaud(Integer.decode(txtBauds.getText()));
                    p.start();
                    break;
                }
            } catch (LineUnavailableException ex) {
                Logger.getLogger(sender.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(curline==null) {
            System.out.println("no source data line found");
        } else {
            System.out.println("sdl found");
        }
    }

    private void close() {
        p.stop();
        p=null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDevices = new javax.swing.JComboBox();
        btnOpenClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBauds = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtMsg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BPSK emitter");

        jLabel1.setText("Audio out :");

        btnOpenClose.setText("Open");
        btnOpenClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCloseActionPerformed(evt);
            }
        });

        jLabel2.setText("Audio freq :");

        txtTone.setText("1000");
        txtTone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToneActionPerformed(evt);
            }
        });

        jLabel3.setText("Hz");

        jLabel4.setText("Baud rate :");

        txtBauds.setText("1200");

        jLabel5.setText("bauds");

        jList1.setToolTipText("Double click to send");
        jScrollPane1.setViewportView(jList1);

        txtMsg.setText("Enter to send");
        txtMsg.setToolTipText("Enter to send");
        txtMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMsgMouseReleased(evt);
            }
        });
        txtMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMsgKeyReleased(evt);
            }
        });

        jButton1.setText("Clear log");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDevices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpenClose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBauds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDevices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBauds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCloseActionPerformed
        // TODO add your handling code here:
        if(p==null) {
            open(Integer.decode(txtTone.getText()));
        } else {
            close();
        }

        txtTone.setEnabled(p==null);
        btnOpenClose.setText(p==null?"Open":"Close");
    }//GEN-LAST:event_btnOpenCloseActionPerformed

    private void txtToneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtToneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToneActionPerformed

    private void txtMsgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMsgKeyReleased
        if(p==null) {
            return;
        }
        if(evt.getKeyCode()==10) {
            p.append(txtMsg.getText());
            txtMsg.setText("");
        }
    }//GEN-LAST:event_txtMsgKeyReleased

    private void txtMsgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMsgMouseReleased
        if(!txtMsgClicked) {
            txtMsgClicked = true;
            txtMsg.setText("");
        }
    }//GEN-LAST:event_txtMsgMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenClose;
    private javax.swing.JComboBox cmbDevices;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBauds;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JTextField txtTone;
    // End of variables declaration//GEN-END:variables
}
