package net.f4grx.audiobpsk;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Line;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.Mixer;
import javax.sound.sampled.SourceDataLine;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author f4grx
 */
public class transmitter extends javax.swing.JFrame {
    
    private boolean txtMsgClicked;
   
    private Player player;
    
    /**
     * Creates new form sender
     */
    public transmitter() {
        initComponents();
        txtMsgClicked = false;
        sldFreq.setMinimum(100);
        sldFreq.setMaximum(10000);
        sldFreq.setValue(1000);
        DefaultComboBoxModel<MixerProxy> lm = new DefaultComboBoxModel<>();
        cmbDevices.setModel(lm);
        
        Mixer.Info[] ms = AudioSystem.getMixerInfo();
        for(Mixer.Info m: ms) {
            Mixer mx = AudioSystem.getMixer(m);
            System.out.println("mixer : "+mx.getMixerInfo().getName());
            Line.Info[] li;
            int src = 0;
            int tgt = 0;
            li = mx.getSourceLineInfo();
            for(Line.Info l: li) {
                src++;
                try {
                    System.out.println("  source: "+mx.getLine(l).toString());
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(transmitter.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            li = mx.getTargetLineInfo();
            for(Line.Info l: li) {
                tgt++;
                try {
                    System.out.println("  target: "+mx.getLine(l).toString());
                } catch (LineUnavailableException ex) {
                    Logger.getLogger(transmitter.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(src>0) {
                lm.addElement(new MixerProxy(mx));
                System.out.println("    added");
            }
        }
    }

    private void open() {
        player=null;
        Line line;
        DefaultComboBoxModel<MixerProxy> mod = (DefaultComboBoxModel<MixerProxy>) cmbDevices.getModel();
        Mixer m = mod.getElementAt(cmbDevices.getSelectedIndex()).getMixer();
        Line.Info[] li = m.getSourceLineInfo();
        Line curline = null;
        for(Line.Info l: li) {
            try {
                line = m.getLine(l);
                System.out.println("  source: "+line.toString());
                if(line instanceof SourceDataLine) {
                    curline = line;
                    player = new Player((SourceDataLine)curline);
                    player.setBaud(Integer.decode(txtBauds.getText()));
                    player.setFreq((double)sldFreq.getValue());
                    player.start();
                    break;
                }
            } catch (LineUnavailableException ex) {
                Logger.getLogger(transmitter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(curline==null) {
            System.out.println("no source data line found");
        } else {
            System.out.println("sdl found");
        }
    }

    private void close() {
        player.stop();
        player=null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDevices = new javax.swing.JComboBox();
        btnOpenClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFreq = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBauds = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        txtMsg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        sldFreq = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BPSK transmitter");

        jLabel1.setText("Audio out :");

        btnOpenClose.setText("Open");
        btnOpenClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCloseActionPerformed(evt);
            }
        });

        jLabel2.setText("Audio freq :");

        lblFreq.setText("5000 Hz");

        jLabel4.setText("Baud rate :");

        txtBauds.setText("1200");

        jLabel5.setText("bauds");

        jList1.setToolTipText("Double click to send");
        jScrollPane1.setViewportView(jList1);

        txtMsg.setText("Enter to send");
        txtMsg.setToolTipText("Enter to send");
        txtMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMsgMouseReleased(evt);
            }
        });
        txtMsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMsgKeyReleased(evt);
            }
        });

        jButton1.setText("Clear log");

        sldFreq.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFreqStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBauds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMsg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sldFreq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbDevices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOpenClose)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(sldFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFreq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDevices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenClose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBauds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, lblFreq, sldFreq});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCloseActionPerformed
        // TODO add your handling code here:
        if(player==null) {
            open();
        } else {
            close();
        }

        btnOpenClose.setText(player==null?"Open":"Close");
    }//GEN-LAST:event_btnOpenCloseActionPerformed

    private void txtMsgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMsgKeyReleased
        if(player==null) {
            return;
        }
        if(evt.getKeyCode()==10) {
            player.append(txtMsg.getText());
            txtMsg.setText("");
        }
    }//GEN-LAST:event_txtMsgKeyReleased

    private void txtMsgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMsgMouseReleased
        if(!txtMsgClicked) {
            txtMsgClicked = true;
            txtMsg.setText("");
        }
    }//GEN-LAST:event_txtMsgMouseReleased

    private void sldFreqStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFreqStateChanged
        if(player==null) {
            return;
        }
        int freq = sldFreq.getValue();
        player.setFreq((double)freq);
        lblFreq.setText(freq+" Hz");
    }//GEN-LAST:event_sldFreqStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenClose;
    private javax.swing.JComboBox cmbDevices;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFreq;
    private javax.swing.JSlider sldFreq;
    private javax.swing.JTextField txtBauds;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables
}
